### ISSUE TITLE
Document technical support roadmap

### ISSUE THREAD

**Issue by mchelen-gov** [presidential-innovation-fellows/covid-screener-federalist#2]
- Who currently provides technical support for this product?
- Until when will they be supporting this product?
- Who if anyone will support it after that time?

**Comment by mchelen-gov** [comment]
@irtazabarlas-pif

**Comment by ghost** [comment]
@irtazabarlas-pif will provide the technical support at the code level till his term-limited assignment is valid as Presidential Innovation Fellow.  At present, it may be valid till Sept 30, 2021.

Given the scope of the application and its relationship to the current pandemic (Covid-19), it is not expected that this application will be needed after Sept 30, 2021.

**Comment by mchelen-gov** [comment]
closed by https://github.com/presidential-innovation-fellows/covid-screener-federalist/pull/3
